# Generated by Django 5.1.2 on 2024-10-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('uid_number', models.CharField(max_length=12)),
                ('birth_date', models.DateField()),
                ('photo', models.FileField(upload_to='agent_photos/')),
                ('uid_doc', models.FileField(upload_to='agent_uid_docs/')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('bank_manager', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('pin_code', models.CharField(max_length=6)),
                ('bank_logo', models.FileField(upload_to='bank_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('pin_code', models.CharField(max_length=6)),
                ('uid_number', models.CharField(max_length=12)),
                ('uid_doc', models.FileField(upload_to='user_uid_docs/')),
                ('user_photo', models.FileField(upload_to='user_photos/')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAssignedToBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.agent')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('about_doc', models.FileField(upload_to='bank_about_docs/')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankPrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('policy_doc', models.FileField(upload_to='bank_privacy_policies/')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='UserAssignedToBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoanAddStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.IntegerField()),
                ('remaining_loan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_close_date', models.DateField()),
                ('agreement_copy', models.FileField(blank=True, null=True, upload_to='loan_agreements/')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserLoanStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.IntegerField()),
                ('emi_add_type', models.CharField(max_length=50)),
                ('added_emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_loan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('amount_type', models.CharField(max_length=50)),
                ('yesterday_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entered_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_add_time', models.DateTimeField()),
                ('request_status', models.BooleanField(default=False)),
                ('confirm_request_accept_date_time', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.agent')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.userdetail')),
            ],
        ),
    ]
