# Generated by Django 5.1.2 on 2024-10-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='agentassignedtobank',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='bankabout',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='bankprivacypolicy',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userassignedtobank',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userloanaddstatement',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userloanstatement',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userpaymentstatement',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='agentassignedtobank',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='bankabout',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='bankprivacypolicy',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userassignedtobank',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userloanaddstatement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userloanstatement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userpaymentstatement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.state'),
        ),
    ]
