# Generated by Django 5.1.2 on 2024-10-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_district_state_alter_agent_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='agentassignedtobank',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_banks', to='bank.agent'),
        ),
        migrations.AlterField(
            model_name='agentassignedtobank',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agents', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='agentassignedtobank',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='agentassignedtobank',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='bankabout',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_info', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='bankabout',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='bankabout',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='bankprivacypolicy',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policies', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='bankprivacypolicy',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='bankprivacypolicy',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userassignedtobank',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='userassignedtobank',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userassignedtobank',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userassignedtobank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_banks', to='bank.userdetail'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userloanaddstatement',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_add_statements', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='userloanaddstatement',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userloanaddstatement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userloanaddstatement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_add_statements', to='bank.userdetail'),
        ),
        migrations.AlterField(
            model_name='userloanstatement',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_statements', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='userloanstatement',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userloanstatement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userloanstatement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_statements', to='bank.userdetail'),
        ),
        migrations.AlterField(
            model_name='userpaymentstatement',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_statements', to='bank.agent'),
        ),
        migrations.AlterField(
            model_name='userpaymentstatement',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_statements', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='userpaymentstatement',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_district', to='bank.district'),
        ),
        migrations.AlterField(
            model_name='userpaymentstatement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_state', to='bank.state'),
        ),
        migrations.AlterField(
            model_name='userpaymentstatement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_statements', to='bank.userdetail'),
        ),
    ]
