# Generated by Django 5.1.2 on 2024-11-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_agent_photo_alter_agent_uid_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.FileField(upload_to='agent_photos/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='uid_doc',
            field=models.FileField(upload_to='agent_uid_docs/'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_logo',
            field=models.FileField(upload_to='bank_logos/'),
        ),
        migrations.AlterField(
            model_name='bankabout',
            name='about_doc',
            field=models.FileField(upload_to='bank_about_docs/'),
        ),
        migrations.AlterField(
            model_name='bankprivacypolicy',
            name='policy_doc',
            field=models.FileField(upload_to='bank_privacy_policies/'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='uid_doc',
            field=models.FileField(upload_to='user_uid_docs/'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_photo',
            field=models.FileField(upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='userloanaddstatement',
            name='agreement_copy',
            field=models.FileField(blank=True, null=True, upload_to='loan_agreements/'),
        ),
    ]
